### ISSUE TITLE
Update nuget package?

### ISSUE THREAD

**Issue by huguesma** [roblevine/UnityLog4NetExtension#11]
Hello,
It's seem that the nuget package is not up to date.
You'll plan to update ?
Thank for your useful lib.

**Comment by roblevine** [comment]
Hi @huguesma,

Are you referring to the fact there's no NuGet package for the Unity v5 branch of the extension? 

If so, that's because there is now an extension which is supported by the Unity team which provides the same functionality as this extension, so I decided to discontinue this for Unity v5.
More info on the replacement here: https://github.com/unitycontainer/log4net.

Let me know if you meant something else - and thank you very much for the positive feedback; it is always very much appreciated.

Rob

**Comment by huguesma** [comment]
@roblevine thx for your answer.
