### ISSUE TITLE
Broken with Unity 4.0.0.0

### ISSUE THREAD

**Issue by stricq** [roblevine/UnityLog4NetExtension#5]
The newly released Unity 4.0.0.0 breaks UnityLog4NetExtension.

**Comment by stricq** [comment]
Still broken with Unity 4.0.1

**Comment by roblevine** [comment]
Thanks for raising this - I haven't been following the changes in Unity 4, but I'll take a look and work out a fix.

**Comment by roblevine** [comment]
I've created a unity-4 branch and updated the extension here to run with Unity 4. 

Can you tell me if this fixes your problem? If not, please can you let me have some more information on what doesn't work?

If this works for you, I'll publish updated NuGet packages for both versions below 4 and for version 4.

Thanks

**Comment by stricq** [comment]
Thanks.  It is working perfectly with Unity 4 now.

**Comment by stevehipwell** [comment]
When will this be deployed to NuGet?

**Comment by stricq** [comment]
Yes, a new NuGet package is needed.  I can run my application locally, but the build server restores NuGet on every run.

**Comment by tiesmaster** [comment]
Works for me too! :+1: 

@roblevine When are you able to ship this?

**Comment by stricq** [comment]
Any updates for this?

**Comment by roblevine** [comment]
Apologies all, I've been on holiday for a fortnight. I'm looking into this now.

**Comment by roblevine** [comment]
OK - I've released two new NuGet packages:

`UnityLog4NetExtension-2.0.1` is the new version which is compatible with Unity v4.
`UnityLog4NetExtension-1.2.1` is the old version which is compatible with Unity versions prior to 4, but now has explicit version constraints for Unity specified in the NuGet.

Can someone please test and let me know if new package(s) are working correctly when pulled from NuGet?

Thanks

**Comment by tiesmaster** [comment]
:+1: Works for me. Thank you very much!!

**Comment by roblevine** [comment]
Excellent! Thanks for testing.

**Comment by stricq** [comment]
A bit late, but the NuGet update worked perfectly for me as well.

**Comment by roblevine** [comment]
In case any of you are interested - I've been investigating the root cause of this issue; why did this new version of Unity stop working with `UnityLog4NetExtension`? It shouldn't have done because there were no actual breaking changes. I'd also noticed that I was unable to force the new Unity version to work with old `UnityLog4NetExtension` by adding a binding redirect in the app.config.

The answer is: Unity v4 has been signed with a different key to previous versions. In other words, the strong name of the assembly is different. 

The previous version of the extension (v1.x.x.x) was compiled against
`Microsoft.Practices.Unity, Version=2.1.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`

The new version (v2.x.x.x) is now compiled against
`Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f`

Quite a few people have complained about this change, it seems the old signing key was not released by Microsoft to the new developers when its development was moved to the community.

The issue of the signing key is being tracked here: https://github.com/unitycontainer/unity/issues/15

**Comment by tiesmaster** [comment]
Yes, indeed. The same applies to the new version of PRISM, they actually deprecate the NuGet packages, and changed the namespaces to drop `Microsoft.Practices` (or whatever). It's nice that Unity didn't do that, but I'm waiting until they'll bite that bullet ;)

Looking at the issue you referenced, Unity might do that as well, at some point... :(
